pygments: true
permalink: /:year/:month/:day/:title
title: My Project Timeline
baseurl: /project-timeline
linked_posts: true

prose:
	# Sets the default folder in Prose.io
	rooturl: "_posts"
	# Sets the default metadata in Prose.io
 	metadata:
		layout: "post"
		published: true
